FROM afni_fedora
RUN dnf install -y gcc gcc-c++ make gsl-devel fftw-devel git
RUN git clone https://github.com/nih-megcore/SAMsrcV5.git /opt/SAMsrcV5
WORKDIR /opt/SAMsrcV5
RUN make
ENV PATH=${PATH}:/opt/SAMsrcV5/bin
#WORKDIR /opt/SAMsrcV5/bin
#RUN make symlinks
#CMD ["/usr/local/bin/triangle"]
